# Generated by Django 2.1.1 on 2018-09-22 09:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=datetime.datetime(2018, 9, 22, 9, 58, 29, 965403, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
