# Generated by Django 2.1.2 on 2018-10-04 02:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='product_quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
